import { JodoCoGeneratedContent } from './types';

/**
 * Deterministic Test Fixture for JodoCo Content Engine & Bridge verification
 */
export const KNOWN_JODOCO_FIXTURE: JodoCoGeneratedContent = {
  metadata: {
    topic: 'Why Creator Marketing Beats Cold Ads',
    originalScriptSummary: 'Traditional advertising suffers from banner blindness and rising CPMs. Creator partnerships build organic goodwill and measurable ROI.',
    targetAudience: 'Growth Marketers & DTC Founders',
    generatedAt: '2026-08-28T08:00:00.000Z',
    contentModelVersion: '1.0.0',
    editorialVersion: '1.0',
  },
  coreReel: {
    title: 'Why Creator Marketing Beats Cold Ads — JodoCo Core Reel',
    hookStrategy: 'Direct contrast between ad fatigue and organic trust',
    totalEstimatedDuration: 25.0,
    scenes: [
      {
        sceneIndex: 1,
        sceneType: 'hook',
        templateMapping: 'Scene1Hook',
        targetDuration: 3.2,
        voiceoverScript: 'Why do banner ads get skipped while creator recommendations go viral?',
        voiceoverStartOffset: 0.1,
        recommendedSfx: [
          { type: 'whoosh', timeOffset: 0.05 },
          { type: 'pop', timeOffset: 0.8 },
        ],
        headline: {
          mainText: 'BANNER ADS VS CREATOR TRUST',
          subText: 'Explained in 20 seconds',
          highlightWords: ['CREATOR', 'TRUST'],
        },
        categoryBadge: 'JodoCo Breakdown',
        explainerPill: 'Brand Strategy • 20s Payoff',
        contentPayload: {
          cards: [
            {
              id: 'hook_tag',
              title: 'Banner Ads vs Creator Trust',
              subtitle: 'The fundamental marketing shift',
              badge: '100% Authentic',
            },
          ],
        },
        visualMetadata: {
          sceneType: 'hook',
          templateMapping: 'Scene1Hook',
          visualConcept: 'Split card contrasting ignored banner ads with trusted creator engagement',
          shotType: 'centered_hero',
          motionStyle: 'snappy_spring',
          transitionType: 'spring_wipe',
          accentColor: '#FF8C73',
          secondaryColor: '#B8A7EA',
          aiVideoPrompt: 'Cinematic studio lighting, modern creator reviewing campaign analytics',
        },
      },
      {
        sceneIndex: 2,
        sceneType: 'problem',
        templateMapping: 'Scene2Brand',
        targetDuration: 3.0,
        voiceoverScript: 'A brand wants people to notice its product. But cold ads get ignored.',
        voiceoverStartOffset: 0.1,
        recommendedSfx: [
          { type: 'chime', timeOffset: 0.1 },
          { type: 'pop', timeOffset: 0.6 },
        ],
        headline: {
          mainText: 'A brand wants people to notice its product.',
          subText: 'The Cold Ad Dilemma',
          highlightWords: ['notice', 'product'],
        },
        categoryBadge: 'Step 1: The Brand Challenge',
        explainerPill: 'Declining Ad ROI',
        contentPayload: {
          cards: [
            {
              id: 'brand_goal',
              title: 'Lumina Skin Botanical',
              subtitle: 'Modern D2C Skincare',
              badge: 'High Quality',
              price: '$42',
            },
          ],
        },
        visualMetadata: {
          sceneType: 'problem',
          templateMapping: 'Scene2Brand',
          visualConcept: 'Floating brand product showcase card surrounded by ad fatigue metrics',
          shotType: 'graphic_focus',
          motionStyle: 'smooth_linear',
          transitionType: 'card_slide_left',
          accentColor: '#FF8C73',
        },
      },
      {
        sceneIndex: 3,
        sceneType: 'solution_creator',
        templateMapping: 'Scene3Creator',
        targetDuration: 4.0,
        voiceoverScript: 'So they partner with a creator who already has the right audience and real trust.',
        voiceoverStartOffset: 0.1,
        recommendedSfx: [
          { type: 'pop', timeOffset: 0.2 },
          { type: 'chime', timeOffset: 1.2 },
        ],
        headline: {
          mainText: 'Partner with a creator who already has the right audience.',
          subText: 'Instead of traditional cold ads:',
          highlightWords: ['creator', 'audience'],
        },
        categoryBadge: 'Step 2: The Solution',
        explainerPill: 'Organic Rapport',
        contentPayload: {
          cards: [
            {
              id: 'creator_card',
              title: 'Maya • Beauty & Wellness',
              subtitle: '185K engaged followers',
              badge: '9.2% Eng. Rate',
            },
          ],
        },
        visualMetadata: {
          sceneType: 'solution_creator',
          templateMapping: 'Scene3Creator',
          visualConcept: 'Creator avatar card glowing with authentic community interaction metrics',
          shotType: 'card_stack',
          motionStyle: 'snappy_spring',
          transitionType: 'card_slide_up',
          accentColor: '#8FE3C0',
        },
      },
      {
        sceneIndex: 4,
        sceneType: 'content_flywheel',
        templateMapping: 'Scene4Content',
        targetDuration: 4.0,
        voiceoverScript: 'Creator creates. Audience watches and trusts. Brand gets genuine notice.',
        voiceoverStartOffset: 0.1,
        recommendedSfx: [
          { type: 'chime', timeOffset: 0.1 },
          { type: 'pop', timeOffset: 1.2 },
          { type: 'rise', timeOffset: 2.5 },
        ],
        headline: {
          mainText: 'The 3-Step Content Flywheel',
          subText: 'Creator creates • Audience watches • Brand gets noticed',
          highlightWords: ['Flywheel'],
        },
        categoryBadge: 'Step 3: The Flywheel',
        contentPayload: {
          phases: [
            { id: 1, label: 'Creator creates authentic video.', tag: 'Phase 1', threshold: 0.33 },
            { id: 2, label: 'Audience engages with real trust.', tag: 'Phase 2', threshold: 0.66 },
            { id: 3, label: 'Brand earns measurable customers.', tag: 'Phase 3', threshold: 1.0 },
          ],
        },
        visualMetadata: {
          sceneType: 'content_flywheel',
          templateMapping: 'Scene4Content',
          visualConcept: 'Progressive 3-step vertical flywheel card animating in sync with voiceover',
          shotType: 'kinetic_text',
          motionStyle: 'kinetic_pop',
          transitionType: 'spring_wipe',
          accentColor: '#B8A7EA',
        },
      },
      {
        sceneIndex: 5,
        sceneType: 'both_sides_win',
        templateMapping: 'Scene5BothSidesWin',
        targetDuration: 4.0,
        voiceoverScript: 'The creator gets funded. The brand gets real reach. Both sides win.',
        voiceoverStartOffset: 0.1,
        recommendedSfx: [
          { type: 'pop', timeOffset: 0.1 },
          { type: 'chime', timeOffset: 1.5 },
        ],
        headline: {
          mainText: 'Both sides benefit when the partnership is right.',
          subText: 'Symmetric value creation',
          highlightWords: ['Both sides', 'benefit'],
        },
        categoryBadge: 'Win-Win Ecosystem',
        contentPayload: {
          cards: [
            {
              id: 'brand_win',
              title: 'Brand Wins',
              subtitle: 'Authentic Reach & Customer Trust',
              badge: 'High ROI',
              bullets: [
                { title: 'Organic credibility over cold banners', icon: 'check' },
                { title: 'Measurable direct-response sales', icon: 'zap' },
              ],
            },
            {
              id: 'creator_win',
              title: 'Creator Wins',
              subtitle: 'Fair Sponsorship & Creative Freedom',
              badge: 'Monetization',
              bullets: [
                { title: 'Partnerships that respect audience trust', icon: 'star' },
                { title: 'Sustainable income for continuous creation', icon: 'heart' },
              ],
            },
          ],
        },
        visualMetadata: {
          sceneType: 'both_sides_win',
          templateMapping: 'Scene5BothSidesWin',
          visualConcept: 'Side-by-side balanced dual comparison cards illustrating win-win dynamics',
          shotType: 'split_screen',
          motionStyle: 'snappy_spring',
          transitionType: 'card_slide_left',
          accentColor: '#FF8C73',
          secondaryColor: '#8FE3C0',
        },
      },
      {
        sceneIndex: 6,
        sceneType: 'bridge_jodoco',
        templateMapping: 'Scene6JodoCo',
        targetDuration: 3.8,
        voiceoverScript: "Right creator. Right audience. Right partnership. That's where JodoCo comes in.",
        voiceoverStartOffset: 0.1,
        recommendedSfx: [
          { type: 'rise', timeOffset: 0.1 },
          { type: 'chime', timeOffset: 1.8 },
        ],
        headline: {
          mainText: "That's where JodoCo comes in.",
          subText: 'The Matchmaking Bridge',
          highlightWords: ['JodoCo', 'Bridge'],
        },
        categoryBadge: 'The Ultimate Matchmaker',
        contentPayload: {
          kineticPhrases: [
            'RIGHT CREATOR.',
            'RIGHT AUDIENCE.',
            'RIGHT PARTNERSHIP.',
            "That's where JodoCo comes in.",
          ],
          cards: [
            {
              id: 'bridge_card',
              title: 'The Creator Marketing Agency',
              subtitle: 'Strategic alignment, contract management, and performance tracking',
              badge: 'Verified Network',
            },
          ],
        },
        visualMetadata: {
          sceneType: 'bridge_jodoco',
          templateMapping: 'Scene6JodoCo',
          visualConcept: 'Pulsing geometric bridge linking Brand and Creator nodes into central JodoCo core',
          shotType: 'centered_hero',
          motionStyle: 'pulsing_glow',
          transitionType: 'zoom_in',
          accentColor: '#B8A7EA',
        },
      },
      {
        sceneIndex: 7,
        sceneType: 'final_cta',
        templateMapping: 'Scene7FinalFrame',
        targetDuration: 3.0,
        voiceoverScript: "Let's Jodo. Visit jodoco.agency to build your next high-impact partnership.",
        voiceoverStartOffset: 0.1,
        recommendedSfx: [
          { type: 'pop', timeOffset: 0.2 },
          { type: 'chime', timeOffset: 1.0 },
        ],
        headline: {
          mainText: 'CONNECT • CREATE • GROW',
          subText: 'Brands × Creators',
          highlightWords: ['Jodo'],
        },
        categoryBadge: 'The Creator Marketing Bridge',
        contentPayload: {
          ctaAction: {
            primaryText: "Let's Jodo.",
            subText: 'jodoco.agency',
            targetUrl: 'https://jodoco.agency',
          },
        },
        visualMetadata: {
          sceneType: 'final_cta',
          templateMapping: 'Scene7FinalFrame',
          visualConcept: 'High-contrast JodoCo signature mark with celebratory particles and interactive CTA lockup',
          shotType: 'logo_lockup',
          motionStyle: 'snappy_spring',
          transitionType: 'cut',
          accentColor: '#FF8C73',
        },
      },
    ],
  },
  carousel: {
    title: 'Why Creator Marketing Beats Cold Ads — 6-Slide Carousel',
    hookAngle: 'Why organic creator partnerships outperform traditional advertising spend',
    totalSlides: 6,
    slides: [
      {
        slideNumber: 1,
        role: 'hook',
        headline: 'Cold Ads are Dying. Here is What Works.',
        subHeadline: 'Why the highest-performing brands partner with authentic creators in 2026.',
        bodyCopy: 'Swipe through to see the exact 3-step flywheel turning creators into high-converting brand advocates.',
        calloutBadge: 'Creator Strategy',
        footerCta: 'Swipe →',
      },
      {
        slideNumber: 2,
        role: 'problem_setup',
        headline: 'The Problem with Direct Banner Ads',
        subHeadline: 'Ad fatigue is at an all-time high.',
        bodyCopy: 'Audiences have developed banner blindness. When a brand interrupts their feed, they scroll right past.',
        bulletPoints: [
          'High CPMs with diminishing conversion rates',
          'Zero organic trust or community goodwill',
          'No ongoing relationship beyond the single impression',
        ],
        calloutBadge: 'The Challenge',
      },
      {
        slideNumber: 3,
        role: 'core_value',
        headline: 'Enter: The High-Trust Creator',
        subHeadline: 'Audiences buy from people they respect.',
        bodyCopy: 'A trusted creator spent years cultivating genuine rapport with their audience. When they endorse a product, it carries organic weight.',
        bulletPoints: [
          'Instant social proof and authentic storytelling',
          'Tailored narrative crafted specifically for their niche',
          'Higher engagement and warm audience resonance',
        ],
        calloutBadge: 'The Solution',
      },
      {
        slideNumber: 4,
        role: 'step_detail',
        headline: 'The 3-Step Content Flywheel',
        subHeadline: 'How the partnership creates compounding value.',
        bodyCopy: '1. Creator Crafts Narrative -> 2. Audience Responds With Real Engagement -> 3. Brand Earns Sustainable Equity.',
        bulletPoints: [
          'Step 1: Authentic creative angle agreed with brand',
          'Step 2: Transparent, community-first content delivery',
          'Step 3: Trackable brand awareness and conversion',
        ],
        calloutBadge: 'The Engine',
      },
      {
        slideNumber: 5,
        role: 'summary',
        headline: 'Symmetric Growth: Both Sides Win',
        subHeadline: 'Creators get funded. Brands get real reach.',
        bodyCopy: 'Sustainable marketing is never extractive. When creator incentives align with brand objectives, long-term brand equity multiplies.',
        calloutBadge: 'The Outcome',
      },
      {
        slideNumber: 6,
        role: 'cta',
        headline: "Ready to Bridge the Gap? Let's Jodo.",
        subHeadline: 'The Creator Marketing Agency.',
        bodyCopy: 'Visit jodoco.agency to match your brand with top-tier verified creators.',
        calloutBadge: 'Next Steps',
        footerCta: 'Connect at jodoco.agency',
      },
    ],
  },
};
